Add friends likes
RuslanRinatovich/java-filmorate pull request #3
Opened 2024-08-01 13:50 UTC by RuslanRinatovich

2024-08-01 15:25 UTC, RuslanRinatovich commented
Отправляю вам на проверку. Не знаю как обойти эти ошибки. В классах  InMemoryFilmStorage и  InMemoryUserStorage есть методы проверки полей классов на валидность. В тестах постмана надо, чтобы приложение возвращало при возникновении ошибок статус 400. (Выставляю throw new ValidationException). тестирую локально. Тесты проходят. Заливаю в гит, но в RunApplication пишет, что ожидался код ошибки 500 если тестировать валидацию(тесты там на корректность полей). Выставляю, как в этом варианте throw new InternalServerErrorException(со статус-code 500).  RunApplication проходит, но когда дело доходит до постмана, логично что в этом случае ожидаемый код 400 и реальный 500 не совпадают. Итого 7 тестов не пройдено.

2024-08-02 08:40 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Для INTERNAL_SERVER_ERROR нужно обрабатывать базовый класс эксепшенов Throwable.
```
@ExceptionHandler
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
public ErrorResponse handleThrowable(Throwable e)
```
смысл в том что обработчик будет искать методы для классов наследников (NotFoundException и т.д.) и если не найдет то возьмет для базового класса Throwable

2024-08-02 08:59 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final Map<Long, Friend> friends = new HashMap<>();
Не оптимально выбрана структура для хранения. Далее ты нигде не используешь ключ мапы для быстрого доступа к элементу, а делаешь все перебором элементов values().stream().
Достаточно будет обычного списка для твоего подхода.
Или предлагаю подумать и рассмотреть такую структуру Map<Long, Set<Long>> где первый параметр это userId а второй это список id друзей без повторов.

2024-08-02 09:02 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Map<Long, Like> likes = new HashMap<>();
здесь таже проблема что и с друзьями.

2024-08-02 09:03 UTC, VadimZharkov requested changes
Нужно использовать более оптимальные структуры для франения друзей и лайков

2024-08-03 05:58 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final Map<Long, Set<Long>> friends = new HashMap<>();
Да, сейчас лучше. И еще архитектурный момент нужно учесть. Хранение данных у нас в классах Storage. Поэтому лучше friends переместить в InMemoryUserStorage, в классах Service остается только бизнес-логика (проверки, преобразоватия, сортировки и т.д.)

Аналогично для лайков

2024-08-03 05:59 UTC, VadimZharkov requested changes
Переместить данные в стораджи

2024-08-04 18:24 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final Map<Long, Set<Long>> friends = new HashMap<>();
Переделал немного архитектуру приложения. Стораджи просто хранят и занимаются добавлением, обновлением и удалением фильмов, пользователей, друзей и лайков. Сервисы занимаются проверкой есть ли в стораджах нужные и ненужные записи, занимаются валидацией. Контроллеры просто получают запросы, проверяют тела запросов(есть ли там параметры и т.д. и т.п). надеюсь я правильно понял логику данной архитектуры.

2024-08-05 06:27 UTC, VadimZharkov approved these changes
Да все верно

2024-08-05 14:33 UTC, merged