Add database
RuslanRinatovich/java-filmorate pull request #8
Opened 2024-08-09 19:26 UTC by RuslanRinatovich

2024-08-10 07:25 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +package ru.yandex.practicum.filmorate.dal;
Что такое dal) может dao

2024-08-10 07:27 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +public class BaseRepository<T> {
Отлично, что сделал базовый класс

2024-08-10 07:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
@Autowired у private final UserService userService; избыточен, т.к. есть конструктор UserController(UserService userService), через него и присоеденится зависимость (заинжектится)

2024-08-10 07:35 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto getUser(@PathVariable(name = "id", required = false) final Long userId) {
Здесь не понятно, required = false а дальше проверяем и говорим, что он должен быть указан

2024-08-10 07:38 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto createUser(@RequestBody User user) {
На вход методов контроллеров мы должны подавать Dto, плюс нужно добавить аннотацию `@Valid`, чтобы тело запроса проверилось на корректность заполнения.

2024-08-10 07:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +    protected Integer insert(String query, Object... params) throws InternalServerErrorException {
Лучше эксепшен назвать DaoErrorException или RepositoryDbException, т.к.  InternalServerErrorException слишком общее название

2024-08-10 08:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmLikeRepository.java
> +    @SneakyThrows
`@SneakyThrows ` заворачивает проверяемые исключения в непроверяемые (в джаве два вида исключений) Чтобы такого не городить сразу сделай InternalServerErrorException наследником от RuntimeException (когда наследник от Throwable это проверяемое исключение, а если от  RuntimeException это непроверяемое).  Непроверяемые мы не обязаны указывать в сигнатуре метода и соответственно  `@SneakyThrows` не понадобится

2024-08-10 08:07 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +            for (Genre g : result) {
Вставлять по одной записи не эффективно. Лучше воспользоваться пакетной операцией (за одно обращение к БД можно вставить несколько записей).
https://habr.com/ru/articles/703828/

2024-08-10 08:11 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +	CONSTRAINT FILM_GENRE_PK PRIMARY KEY (GENRE_ID,FILM_ID)
правильно что не стал делать суррогатный первичный ключ

2024-08-10 08:12 UTC, VadimZharkov requested changes
Можно улучшить

2024-08-10 11:37 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +package ru.yandex.practicum.filmorate.dal;
я дела по аналогии с проектом catsgram, там есть папка dal(data acsess layer - слой доступа к данным)
![image](https://github.com/user-attachments/assets/f35b5666-e677-4774-8e65-8d854705ba93)

2024-08-10 11:37 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +package ru.yandex.practicum.filmorate.dal;
переименую в repository

2024-08-10 11:40 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +public class BaseRepository<T> {
done)

2024-08-10 11:41 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
deleted)

2024-08-10 11:53 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto getUser(@PathVariable(name = "id", required = false) final Long userId) {
убрал во всех методах, кроме getMostPopularFilms

2024-08-10 11:54 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto getUser(@PathVariable(name = "id", required = false) final Long userId) {
убрал

2024-08-10 12:57 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +    protected Integer insert(String query, Object... params) throws InternalServerErrorException {
done)

2024-08-10 12:57 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmLikeRepository.java
> +    @SneakyThrows
done)

2024-08-10 13:39 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto createUser(@RequestBody User user) {
добавлено)

2024-08-10 13:59 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +            for (Genre g : result) {
доне)

2024-08-10 14:12 UTC, RuslanRinatovich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto createUser(@RequestBody User user) {
Как можно добавить в аннотацию к дате, типа 
@Min(value = "1985.12.01") 
LocalDate primerDate;

Была идея преобразовать налету LocalDate d UNIXtime(типа Long) и от этого отталкиваться, попытался сделать, не очень заработало.
@Min(value = -2222222222L) 
Long primerDate;

в Mapper преобразовывал в таком стиле
ZoneId zoneId = ZoneId.systemDefault(); // or: ZoneId.of("Europe/Oslo");
long epoch = date.atStartOfDay(zoneId).toEpochSecond();

2024-08-11 08:14 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserDto createUser(@RequestBody User user) {
Что-то подобное будет в 15 ой работе. Смысл в том чтобы сделать свою аннотацию и класс валидатор для нее.

2024-08-11 08:14 UTC, VadimZharkov approved these changes

2024-08-11 17:33 UTC, merged